dist: precise

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - TYPO3_VERSION="^6.2.0"
  - TYPO3_VERSION="^7.6.0"
  - TYPO3_VERSION="^8.7.0"

matrix:
  exclude:
    - php: 5.3
      env: TYPO3_VERSION="^7.6.0"
    - php: 5.4
      env: TYPO3_VERSION="^7.6.0"
    - php: 5.3
      env: TYPO3_VERSION="^8.7.0"
    - php: 5.4
      env: TYPO3_VERSION="^8.7.0"
    - php: 5.5
      env: TYPO3_VERSION="^8.7.0"
    - php: 5.6
      env: TYPO3_VERSION="^8.7.0"
    - php: 7.0
      env: TYPO3_VERSION="^6.2.0"
    - php: 7.1
      env: TYPO3_VERSION="^6.2.0"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;