<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mail_spool"
 *
 * Auto generated by Extension Builder 2015-12-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Mail Spool',
    'description' => 'Integrates swiftmailer spool transport for TYPO3.',
    'category' => 'misc',
    'author' => 'R3 H6',
    'author_email' => 'r3h6@outlook.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.99.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
